export const DomainErrorCode = {
  DEPARTURE_NOT_FOUND: "DEPARTURE_NOT_FOUND",
  DEPARTURE_FULL: "DEPARTURE_FULL",
  DEPARTURE_CLOSED: "DEPARTURE_CLOSED",
  DEPARTURE_NOT_OPEN: "DEPARTURE_NOT_OPEN",
  DEPARTURE_OPEN: "DEPARTURE_OPEN",
  INVALID_PARTY: "INVALID_PARTY",
  POLICY_NOT_ACKNOWLEDGED: "POLICY_NOT_ACKNOWLEDGED",
  MEDICAL_REQUIRED: "MEDICAL_REQUIRED",
  EXPERIENCE_REQUIRED: "EXPERIENCE_REQUIRED",
  EMERGENCY_CONTACT_REQUIRED: "EMERGENCY_CONTACT_REQUIRED",
  PRICE_INVALID: "PRICE_INVALID",
  STAFF_NOT_FOUND: "STAFF_NOT_FOUND",
  STAFF_INACTIVE: "STAFF_INACTIVE",
  STAFF_FORBIDDEN: "STAFF_FORBIDDEN",
  INVENTORY_CONFLICT: "INVENTORY_CONFLICT",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  BOOKING_NOT_CANCELLABLE: "BOOKING_NOT_CANCELLABLE",
  INVALID_TRANSITION: "INVALID_TRANSITION",
  REASON_REQUIRED: "REASON_REQUIRED",
  ENQUIRY_INVALID: "ENQUIRY_INVALID",
  CONTENT_INVALID: "CONTENT_INVALID",
} as const

export type DomainErrorCode = (typeof DomainErrorCode)[keyof typeof DomainErrorCode]

export class DomainError extends Error {
  readonly code: DomainErrorCode

  constructor(code: DomainErrorCode, message: string) {
    super(message)
    this.name = "DomainError"
    this.code = code
  }
}
